### ISSUE TITLE
那个工程是启动项目呀，萌新求指导。

### ISSUE THREAD

**Issue by wsxjbupt** [electronicarts/CnC_Remastered_Collection#106]

**Comment by WIAIHE** [comment]
You should use english

**Comment by juliusfriedman** [comment]
令人遗憾的是Github在2021年不提供翻译服务，您可以在此处寻求指导，而在其他地方可以找到它

**Comment by KSroido** [comment]
你大概是计算机大学新生吧,不过没关系,GitHub是这样的:提问和PR都需要使用英文,这样才会有更多的人能够帮助你

**Comment by juliusfriedman** [comment]
XD, 小心点，甚至父母都是那个时代的学生
