### ISSUE TITLE
TXT_IRON_CURTAIN undeclared identifier

### ISSUE THREAD

**Issue by xiangzhai** [electronicarts/CnC_Remastered_Collection#11]
Hi,

[TXT_IRON_CURTAIN ](https://github.com/electronicarts/CnC_Remastered_Collection/blob/master/REDALERT/BDATA.CPP#L270) undeclared identifier for Release WIN32 Rebuild:

```
d:\project\xiangzhai\cnc_remastered_collection-master\redalert\bdata.cpp(270): error C2065: 'TXT_IRON_CURTAIN': undeclared identifier
```

Windows 10 Home edition
Visual Studio Community 2017
Windows 8.1 SDK

Thanks,
Leslie Zhai

**Comment by sexdevil** [comment]
I solved the problem by manually include "../REDALERT/CONQUER.H" in REDALERT/BDATA.CPP,  it seems when REDALERT do compling  ,it  included the TIBERIANDAWN/CONQUER.H .

**Comment by xiangzhai** [comment]
@sexdevil Thanks!
