### ISSUE TITLE
Where's the binary exe?

### ISSUE THREAD

**Issue by Hydra9268** [electronicarts/CnC_Remastered_Collection#13]
I am able to build without issues. However, I don't see an EXE file. Is that not included in the solution?

https://i.imgur.com/wim4rDC.jpg

I'd love to set breakpoints and learn how the engine works. :)

**Comment by TuomasHeikkila** [comment]
The project compiles into a .dll file, a set of functions that can be imported into other projects, such as the actual game project for Red Alert or Tiberian Dawn. 

EA hasn't released RA and TibDawn as open source games, just their respective "rules engines".

What you could do is buy the remastered collection, make a debug version of the DLL, swap the DLL's in your installation folder and debug that. 

https://www.reddit.com/r/commandandconquer/comments/gnevp8/remaster_update_and_open_source_mod_support/

**Comment by Hydra9268** [comment]
That's makes cents. ;)
