### ISSUE TITLE
CodePage error when loading file

### ISSUE THREAD

**Issue by techboy203** [electronicarts/CnC_Remastered_Collection#20]
Load file error because encoding not compatiable, for example like "COMBUF.cpp".
What is the original CodePage?
I'm compiling in chinese windows 10 op system.

**Comment by cubesky** [comment]
Use VSCode or other editor convert its codepage from `Western (Windows 1252)` to `UTF-8`

**Comment by HnlyWk** [comment]
doushi cha inese

**Comment by khm1600** [comment]
The original encoding is identified as `DOS (CP 437)` in vsc. 
I would assume the original encoding is (Windows) code page 437 instead 1252.

**Comment by techboy203** [comment]
> Use VSCode or other editor convert its codepage from `Western (Windows 1252)` to `UTF-8`

Thanks，your solution is worked.
