### ISSUE TITLE
Are there any utilities/editors that can open the game's .MEG archives?

### ISSUE THREAD

**Issue by Capt-Nemo-** [electronicarts/CnC_Remastered_Collection#29]
There are plenty for opening the old .MIX files but these seem to be some new format. Is there a specification at least? Or are they not intended to be modded?

**Comment by GraionDilach** [comment]
I've had success with https://modtools.petrolution.net/tools/MegEditor on MUSIC.MEG so I suspect any tool you'd be able to google up with "Petroglyph MEG" format would work.

**Comment by Capt-Nemo-** [comment]
It works, nice find thanks!
