### ISSUE TITLE
Full Red Alert Dubbing in both Chinese and English[红色警戒配音中/英文]

### ISSUE THREAD

**Issue by JasonkayZK** [electronicarts/CnC_Remastered_Collection#30]
生产(Production)：
　　没钱了 Insufficient funds
　　可以造新东西了 New construction options
　　开始建造建筑物 building
　　开始生产作战单位 Training
　　暂停生产 On hold
　　取消生产 Canceled
　　生产进行中 目前不接受新的生产指令 Can not comply building in progress
　　建筑已造好 Construction complete
　　单位已造好 Unit ready　　
       建筑被卖掉 Structure sold
　　建筑修理 Repairing
　　电力不足 生产减缓 Low power
　　选定主要建筑物（战车工厂/兵营等）Primary building selected

作战(Fighting)：
　　单位已修好 Unit repaired
　　单位升级了 Unit promoted
　　作战单位被灭 Unit lost
　　（战车工厂/兵营/维修厂）建立新的集结点 New ___  point established
　　我们的建筑物正遭受攻击 Our base is under attack
　　援军（空降部队）准备好了 Reinforcements ready
　　进入该建筑 盗得金钱 Building ininfiltrated cash stolen
　　进入该建筑 盗得科技 Building ininfiltrated New technology acquired
　　进入该建筑 敌方电力切断 Building ininfiltrated enemy base power down
　　进入该建筑 敌方雷达探明 Building ininfiltrated radar subtouched
　　占领（敌方）建筑 Building captured
　　占领科技（油井 空降场等）建筑 Tech building captured
　　（油井 空降场等）建筑被敌占领 Tech building lost
　　被敌方盗得金钱 Cash stolen
　　桥梁已修好 Bridge repaired
　　大兵驻扎建筑物 Structure garrisoned
　　脱离驻扎建筑物 Structure abandoned
　　（超级武器）选择目标 Select target
　　玩家被击败 Player defeated
　　你胜利了 You are victorious

*盟军男平民(Allied male civilians)
　　WhatshouldIdo?我该做什么？
　　Thisisscary.这是骇人的
　　I‘lldoit.我将做它
　　Isee‘em.我看见他们
　　Youbet.你打赌

*盟军女子(Allied female civilians)
　　Whatdoyouwant.你想要什么。
　　Ilikeamaninuniform.我喜欢穿制服的人。
　　Likemynewhaircut?喜欢我的新发型吗？
　　CanIbringmyfriends?我能带我的朋友吗？
　　Alright.好的。
　　Let‘sgo!让我们走！
　　Myfeethurt.我的脚痛了。
　　Ifyousayso如果你这样说（我就做）
　　DoIhaveto?，我要做？
　　IsthisaREALgun?这是支真枪吗？
　　WillIgethurt?我将受伤吗？
　　Ijustboughtthisoutfit.我只是买了这装备。
　　Hey,cutitout.嗨,让它离开。
　　Iwasonlykidding!我仅仅在开玩笑！

*俄男平民(Russian male civilians)
　　WhereshouldIgo?我应该去哪？
　　You‘rewish?你的愿望吗？
　　Itis,safe?是这，安全吗？
　　Ihearandobey.我听到并且服从。
　　Firing.开火
　　Forthecommongood.为了共同的好处。
　　Iwilldoasyousay.我将做，正如你所说。

*俄妇女(Russian female civilians)
　　Da俄语的是[猜的]
　　Whatisit?这是什么？
　　I‘mcold.我很冷。
　　AreyouKGB?你是克格勃（成员）吗？（苏联类似FBI的特工组织）
　　Whatasociety.多好的社会。
　　I‘llbelateforbreadline.（这样）我排粮队会迟到的。
　　ButIwasworking.但是我还在工作呀。
　　NorestforSovietwomen.苏维埃妇女不休息。
　　Wherearewegoing?我们正在去哪？
　　IfImust.如果我必须。
　　Willyouwatchmychildren?你照看我的孩子吗？
　　Itismyduty.它是我的责任。 ForRomanov.为了诺曼罗夫（RA2中的苏联总理）。
　　I‘mjustawoman.我只是一个女人呀。
　　Iknewthiswouldhappen.我知道这将发生。

*牛仔(cowboy)
　　Iain‘tyeller.我忍不住大叫（依~~~哈~~~）。
　　Likemybeltbuckle.喜欢我的“带扣环”。[猜的]
　　Heypartner!嗨，伙伴！
　　Where‘smahorse?我的马在哪里？[应该是吧]
　　Let‘smosey.让我们闲逛。
　　Gittin‘along.……向前？
　　Hittin‘thetrail.发现痕迹[猜的]
　　Timeforashowdown.对决的时间到了。
　　Fastestguninthewest.西部最快的枪。
　　Readytodraw.准备好了平局。[猜的]
　　I‘mbein‘bushwhacked!我被伏击！
　　Varmitshotme!混蛋射击我！
　　Gonnadieinmyboots!我要死了！

*超级保镖(Executive Protection)
　　I‘lltakethebullet.我将带上子弹。
　　Agentinthefield.顾主在场上。
　　Secretservicehere.这里是“经情局”（美特务机构）。
　　Needanescort?需要护卫吗？
　　Assigmentsir?委派，先生？
　　What‘syourclearancelevel?你的“清理”水平怎样？
　　Securingthearea.放心这区域。
　　Scanningperimeter.扫描周边（情况）。
　　Rightawaysir.马上，先生。
　　Assignmentrecieved.任务收到。
　　He‘sdoesn‘tbelonghere.他不属于这儿。
　　He‘sathreat.他是个威胁。
　　Nowitnesses.没有证人。
　　Shoottokill.枪毙。
　　Executingassignment.执行任务。

*恐怖分子(terrorist)
　　Whatareyourconditions?你开的条件是？
　　Wemustrevolt.我们必须反抗。
　　Needasmuggler?需要秘密运输船吗？
　　VamosMuchachos!冲！
　　Igofreely.我自由地去。
　　Adiosamigos!再见，朋友！
　　Here‘sahotpapaya!这有个火热的番木瓜！（蘑菇云？）
　　Fortherepublic!为了共和国！
　　Traitorsmustbeeliminated!叛徒必须被清除！
　　TakemebacktoHavana!把我带回到哈瓦那（古巴首都）！
　　I‘vebeendiscovered!我被发现了！

*美国大兵(American soldier)
　　Siryessir!长官，是长官！
　　Ready!准备好了！
　　Squaredawaysir!正远方，长官！
　　Orders?命令是？
　　How`boutsomeaction?来一些行动，怎么样？
　　Cando!能干！
　　Who‘snext?下一个是谁（目标）？
　　Move‘nout!移动并出去[猜的]
　　Gotit!拿下它！
　　Onmyway!正在路上！
　　Doubletime!快跑时间！
　　Onthemove!在移动中！
　　Attacking!正在攻击！
　　Yougotit!你干掉它！
　　Enemysighted!敌人已看见！
　　Let‘sdoit!让我们行动！
　　Diggin‘in!渗人里面！
　　Safetyfirst,sir!安全第一,长官！
　　We‘repinneddown!我们被压制了！
　　We‘rebeingattacked!我们正在被攻击！

*动员兵(Mobilizers)
　　Waitingorders.等待命令中。
　　Comrad?同志？
　　Conscriptreporting.动员兵报告。
　　Movingout.开始行动
　　Orderreceived.命令收到。
　　FortheUnion.为了（苏维埃）联盟。
　　Forhomecountry.为祖国。
　　Youaresure?你肯定？
　　FormotherRussia!为母亲俄罗斯！
　　Mommy!妈妈呀！
　　We‘rebeingattacked!我们正被攻击！

*盟军工程师(Allied Engineer)
　　Engineering.工程中。
　　Ihavethetools.我有工具。
　　I‘vegottheknowledge.我有知识。
　　Needarepair?需要修理吗？
　　Yessir!是，长官！
　　Moving.移动中。
　　Iwon‘tbelate.我不会迟到的。
　　We‘llhavethepowerupin30seconds,sir.我们将在30秒内供电,长官。
　　Analyzingschematics.分析图表中。
　　Studyingblueprints.正在学习蓝图。
　　Gottheplansrighthere.恰好在这里得到了计划。
　　Getmeoutahere!让我离开这！
　　I‘munarmed!我是徒手的!（还说别人不人道？）

*苏军工程师(Soviet Engineer)
　　Toolsready.工具已备齐。
　　Ihavetheinformation.我知道信息。
　　Somethingneedfixing?有些东西需要修理？
　　Iknowhowitworks.我知道它怎么工作。
　　YesCommander!是的，指挥官！
　　Iwillgo.我就去。
　　Checkingdesigns.检查方案。
　　Examiningdiagrams.检验图表。

*磁暴步兵(Tesla Trooper)
　　Teslasuitready!磁暴服装穿好！
　　Extracrispy.非常易碎。
　　Chargingup.充能中。
　　Electrodesready!电极就绪！
　　Checkingconnection.检查连接。
　　Goingtosource.去发源地。
　　Yescomrade.是的，同志。
　　Surgingforward.向前挺进。
　　Electricianinthefield.战场上的“电工”。
　　Rubbershoesinmotion.穿着橡胶鞋子运动（走着别扭？）。
　　2,000voltscomingup.2000伏高压来了
       He‘sfried.他被“油炸”了。
　　Completingcircuit.完善电路中。[放电？猜的]
　　Letthejuiceflow.让液体流动起来。
　　CommencingShocktherapy.开始电震疗法。
　　Congratulations!祝贺！
　　You‘vebeendischarged.你被放电了。
　　Groundyourselves!土地是你们自己的！
　　Reinforcements!增援！
　　I‘mhit!我被打了！

*飞兵(Flying soldier)
　　Rocketsinthesky.在天空飞升。
　　AllFiredup!全部点火！
　　Checkouttheview.检查视野。
　　Icangoanywhere!我能去任何地方！
　　Gottaclearview,sir.必须视野广阔,长官。
　　Readytosoar.准备好了滑翔。
　　Fueltanksarefilled.燃料罐是充满的。
　　Pushin‘away.冲呀[猜的]
　　Ignitingboosters.推进器点火。
　　RidingHigh.高空乘骑。
　　Upandover.升高并越过。
　　Gotasteadyflow.得到了稳定的漂移。
　　I‘lltakethehighroad.我将控制空路。
　　Liftingoff.停止上升。
　　He‘sgotnoplacetohide.他没地方隐蔽。
　　Icansee‘em.我能看见他们。
　　Igot‘emClearouttheplace.我把他们清除出这区域。
　　Theywon‘tseeuscomin.他们不会看见我们来了。
　　I‘mlosingcompression!我的压缩机正在受损！
　　There‘stoomuchflak!那儿的防空火力太猛！
　　Myrocket‘shit!我的推进器被打中了！

*防空步兵(Flak trooper)
　　Flaktrooperreporting.防空兵报到。
　　ready.就绪。
　　Orderscomrad?命令？同志。
　　AtleastIhaveajob.至少我有一个工作了。
　　Iamgoing.我正在去。
　　Movingout.移过去。
　　Thisgunisheavy.这支枪很沉呀
　　Flak_attack.对空攻击。
　　Thiswillbemessy.这将混乱。[猜的]
　　Cloudsofdeath.死亡之云。
　　Flakyou.射下你。
　　Can‘tseethroughtheflak.看不到高射炮火后（的东西）。
　　Thereshootingme.那儿在射击我。
　　HelpmeRomanov.救我，诺曼罗夫（RA2中的苏联总理）。
　　I‘mjustoneman.我只是个人而已。

*间谍(spy)
　　Commander?指挥官？
　　Missionsir?任务，长官？
　　Gimmeaplan.给我一个计划。
　　Agentready.准备好了装扮。[猜的]
　　ForKingandCountry.为总统和国家。
　　Indeed.当然。
　　Undercover.隐藏着。
　　Operationunderway.实施行动。
　　Disguiseready.伪装好了。
　　Readytoinfiltrate.准备好了渗透。
　　Obtainingintelligence.获取谍报中。
　　Theyfoundmeout!他们发现了我！
　　I‘vebeenspotted!我被揭穿了！ 

*疯狂伊文(crazy ivan)
　　HappyBirthday!生日快乐！（送你一个爱的礼物：）
　　Here,holdthis.这儿,拿好。 Ilostabomb.我少了一个炸弹
　　Doyouhaveit?你有它吗？（没有就送你一个）
       Don‘tplaywithmatches.别玩火柴。（这还了得……）
　　I‘mgoin‘.我正在过去。
　　What‘soverhere?这里有什么？
　　K－BOOM!（开爆？：）
　　What‘sthat?那是什么？
　　Ivan‘snothome!伊文不回家！[猜的]
　　It‘stooquiethere.这里是太安静了吧。（打红警就得这么想：）

*海豹部队(Seal force)
　　SEALready.“海豹”准备好了。
　　I‘myourman.我是你的人。
　　Alil‘C4knockin‘atyourdoor.一个小C4炸弹在敲你的门。[猜的]
　　Who‘syourdaddy?你父亲是谁？
　　Coverme.掩护我。
　　Howaboutaswim?游泳怎么样？
　　Alright,thewater‘swarm!好的,水挺温暖！
　　Enemyinmysites!敌人我的地盘上！
　　Igot`em.我干掉了他们。
　　Thisistooeasy.这是太容易啦。
       SpecialDelivery!（炸弹）专递！
　　oin‘down!下沉吧！
　　Let‘sgetiton!让我们进行吧！[猜的]

*辐射工兵(Radiation Engineer)
　　Desolatorready.辐射炮准备就绪。
　　Readyformelt－down.准备好了去溶化。
　　Reactorready.反应堆就绪。
　　Mercuryrising.水银上升。
　　Findahotspot.找一个热闹区域。
　　ScorchedEarth.全部烧焦。
　　SpreadtheDoom.展开末日。
　　Theregoestheneighborhood.他在这附近。[猜的]
　　It‘llbeaSilentSpring.它将沉默的爆发。[猜的]
　　Taggedforextinction.消灭目标。
　　Makeitglow.让它发光。（变绿）
　　Let‘sheat`emup.让我们使他们热起来。
　　Herecomesthesun.这里出太阳了。
　　Theendisnear.死期将近。
　　Let‘smakeanoasisofdeath.让我们造个“死亡绿洲”。

*阻击手(Sniper)
　　Sniperready.狙击手就绪。
　　Givemeatarget.给我一个目标。
　　Gimmeajob.给我一个工作。
　　Eliminate‘em.清除他们。
　　Proceedingtovantagepoint.跑到有利地势去。
　　Justgimmeaclearview.只要给我一个广阔的视野
　　Ilovetocamp.我喜欢“蹲点”。
　　Justgetmecloseenough.只须让我靠的足够近。
　　Settlingin.迁入中。[猜的]
　　Takin‘‘emout.拿下他们。
　　He‘sinmyscope.他在我的射程内。
　　He‘sadeadman.他是个死人了。
　　Runforcover!为保命撤退！
　　Ineedsupport!我需要支援！
　　I‘mintooclose!我靠的太近了！

*超时空军团兵(Chrono Legionnaire)
　　Yes,Commander.是的,指挥官。
　　Alreadythere.已经在那里。
　　I‘mgone.我去了。
　　Pickaspot.挑一个地点。
　　Withoutatrace.没有踪迹。
　　They‘rehistory.他们成为历史。
　　DeconstructingNeverexisted.分解中决不存在。
　　Removing.消除中。（送进“超时空”啦）
       Idon‘thavetimeforthis!我没时间干这个！
　　Let‘sgetoutahere!让我们离开这！

*潭雅(Tanya)
　　Anytimeboss.任何时候，老板。
　　Yougotanorder?你得到了命令？
　　Where‘stheparty?“聚会”在哪儿？
　　Showmetheway.给我指路。
　　How‘boutsomeaction.来一些行动，如何？
　　I‘mthere.我在那里。
　　Howaboutatarget?!找个目标怎样?！
　　Movingoutboss.移过去，老板。
　　I‘monit.我在它附近。[猜的]
　　Shakeitbaby!摇它，宝贝儿！[猜的]
　　Cha－Ching![不知]
　　Lockedandloaded.锁定并装弹。
　　YaahBaby!呀~宝贝儿！

*尤里(Yuri)
　　Psychicready.心灵控制准备就绪。
　　Iknowyourthoughts.我知道你的想法。
　　Tellmeyourwish.告诉我你的愿望。（知道了还问？）
　　Yourmindisclear.你的头脑很清晰。
　　Theindisquickerthantheeye.精神比眼来的快。
　　Yes,ofcourse.是的，当然。
　　Predictable.可预测的。
　　Thoughtsreceived.想法收到了。
　　Mycommandisyourwish.我的命令就是你的愿望。
　　Hebelongstous.他将属于我们。
　　Hismindisweak.他的精神力很弱。
　　Thereisnoresistance.这没有反抗。
　　Anewcomradejoinsus.一个新同志加入我们了。
　　Lookdeeplyintomyeyes深深地看着我的眼睛。

*盟军车辆(Allied Tanks)
　　DestinationCommander?目的地？指挥官
　　Readytoroll!准备滚动！
　　Yessir.是，长官。
　　Unitreporting!部队报到！
　　Vehicleready.车辆就绪。
　　Boundforward!往前开
　　Outstanding!等待中！
　　Onourway,sir.在我们的路上，长官。
　　Highspeed,lowdrag.高速度,低拖延。
　　Goodtogo!正好上路！
　　SecuringPosition!固定位置！
　　Firezoneconfirmed.开火区域确认。
　　Driverup!传动器开动！
　　Closingin!接近中！
　　Commencingassault!开始袭击！
　　Weaponready.武器准备好了。

*苏军车辆(Soviet Tanks)
　　Awaitingorders.等候命令。
　　Readycomrade.准备好了，同志。
　　Vehiclereporting.车辆报到。
　　Changingposition.改变位置中。
　　Moving.移动中。
　　Locationconfirmed.地点已确认。
　　Attacking!攻击！
　　Wewillburythem.我们将埋葬他们。
　　Encountingenemy.结束敌人。

*自爆卡车(Demolition Trucks)
　　Whydon‘tyoudrive.为什么你不开车。
　　Ishallavengeus!我将替我们报仇！
　　Let‘smakeadelivery!让我们去“交货”！
　　Mytruckisloaded!我的卡车已装载！
　　Watchoutforthebumps.小心碰撞。[易燃、易爆、轻举轻放]
　　Asyouwish.象你希望一样。
　　Onewaytrip.一次远行。
　　Don‘twaitupforme.别停下等我。
　　Itwillbeasmokingcrater.它将成为冒烟的弹坑。
　　Iampreparedtodie!我准备好了就义！
　　Formypeople!为我的人民（自爆）！

*入侵者战机(Intruder aircraft)
　　Pilotreporting.飞行员报告。
　　Destination?目的地？
　　Channelclear.频道清晰。
　　Aircraftreporting.飞机报告。
　　Likethewind.象风一般。
　　Changingvector.改变引导。
　　Thrustersengaged.推进器开动了。
　　Willco.再联系。[猜的]
　　Instrumentslockedon.器械已锁定（目标）。
　　We‘regoin‘in.我们正在过去。
　　Wehave‘monradar.我们出现在雷达上。
　　Watchmysix.看我的“6”。
　　Readytostrike!准备好打击！
　　We‘regoingdown.我们正在坠落。
　　Bailout!跳伞！
　　Eject!Eject!弹出！快弹出！

*黑鹰战机(Black Eagle)
　　Korea‘sfinest.韩国的（黑鹰）最好。
　　Eaglesquadron.黑鹰中队
　　BlackEaglereporting.黑鹰报告。
　　Atyourservice.为你服务。
　　Standingby.等待。
　　Calibratingairspeed.校准飞行速度。
　　Intransit.正在经过。
　　Commandreceived.命令收到。
　　Easytarget!简单的目标！
　　Gunnerinposition.炮手就位。
　　Let‘stake‘mout.（已爆）让我们出去。

*基洛夫空艇(Kirov Airship)
　　Heliummixoptimal.氦已最佳混合。
　　Airshipready.飞艇就绪
　　Acknowledged.接受（指示）。
　　Kirovreporting.基洛夫报到。
　　Bearingsset.方向设定。
　　Maneuverpropsengaged.机动支持工作中。
　　Settingnewcourse.设定新路线。
　　Bombardierstoyourstations.在你的位置投弹。
　　Closingontarget.锁定目标。
　　Targetacquired.目标已获取。
　　Bombingbaysready.准备好了轰炸。
　　Duckandcover!躲避和保护
　　She‘sgonnablow!她将要漏气。
　　We‘relosingaltitude!我们正在失去高度！
　　Mayday!Mayday!求救！求救（信号）！

*夜鹰运兵机(Nighthawk helicopter)
　　What‘syourrequest?你的要求是什么？
　　Pick‘mup,set‘mdown.让我上,让我下。
　　Airtransportready.空运准备好了。
　　Needalift?需要空运吗？
　　Visibilityclear.能见度开阔。
　　Tourunderway.航行中。
　　Gotcha.我将得到你。
　　Maneuversinprogress.机动前进中。
　　LZishot.着陆区是“火热”的。
　　Clearingapath.清除一条路径。
　　Fireonsight.看见就打.

*盟军战舰(Allied warship)
　　Standingby.等待中。
　　Captainonthebridge.船长在梁上。
　　Navigationsystemsready.航行系统就绪。
　　AlliedShipreporting.盟军船报告。
　　Steadyasshegoes.象她行动一样稳定。
　　Ayecommander.是司令。
　　Ruddersetfornewheading.向新目标转舵。
　　Mainenginesengaged.主引擎开动中。
　　Speedtofull.全速（前进）。
　　Battle－stations!进入战斗岗位！
　　Attacking.攻击中。
　　Enemyspotted.敌人发现。

*苏军战舰(Soviet warships)
　　YesCommander?什么？指挥官。
　　Vesselready.导弹准备好了。
　　Shipreporting.舰船报告。
　　Enginesengaged.引擎使用中。
　　Navigating.航行中。
　　Courseset.路线已设定。
　　Captainconfirming.船长确认中。
　　Closeandfire!接近并开火！
　　Fireatwill.随意开火。
　　Targetsighted.目标已发现。

**Comment by JasonkayZK** [comment]
满满的回忆~

**Comment by 040712zhou** [comment]
看来中国玩家很多，但也暴露了年龄

**Comment by JasonkayZK** [comment]
> 
> 
> 看来中国玩家很多，但也暴露了年龄

哈哈，是的！

**Comment by abergmeier** [comment]
I have an initial commit to get to Unicode support: https://github.com/electronicarts/CnC_Remastered_Collection/pull/33

**Comment by Xuyiyang23333** [comment]
Mark.

**Comment by apple601601601** [comment]
看了前面一点，发现两处错误:
New **rally** point established
进入该建筑 敌方雷达探明 Building ininfiltrated radar **sabotaged**

**Comment by JasonkayZK** [comment]
> 看了前面一点，看着看着忍不住就模仿游戏里的声音念出来了哈哈。。。发现几处错误:
> 
> New **rally** point established
> 
> 进入该建筑 敌方雷达探明 Building ininfiltrated radar **sabotaged** 
> 
> What‘syourclearancelevel?你的“清理”水平怎样？(这里应该是你的保密等级是多少？ 相应的密级可以接触的保密材料不同)

很多内容来自网络，我也记不太清了。所以在校对的时候可能很多错误还是没有找到。( 0 x 0 )

**Comment by Tomyunfei** [comment]
爷青结

**Comment by XiaomingXu1995** [comment]
有声音的issue

**Comment by WestRiverLin** [comment]
爷青回

**Comment by chenyu86784** [comment]
哈哈 爷青回

**Comment by hanxueda** [comment]
当时就知道个building...

**Comment by yangxujia** [comment]
优秀

**Comment by yangxujia** [comment]
自己编译得了吗？在vs2013环境

**Comment by StandNorthStar** [comment]
自带音效

**Comment by 960PRO** [comment]
都是青春回忆啊，祝各位红警玩家游戏快乐

**Comment by yangxujia** [comment]
最终编出来只是一个动态库，你们有完整的源码吗



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 960PRO <notifications@github.com&gt;
发送时间: 2020年6月11日 14:36
收件人: electronicarts/CnC_Remastered_Collection <CnC_Remastered_Collection@noreply.github.com&gt;
抄送: yangxujia <yangxujia@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[electronicarts/CnC_Remastered_Collection] Full Red Alert Dubbing in both Chinese and English[红色警戒配音中/英文] (#30)





 
都是青春回忆啊，祝各位红警玩家游戏快乐

**Comment by cheenng** [comment]
> 最终编出来只是一个动态库，你们有完整的源码吗 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: 960PRO <notifications@github.com&gt; 发送时间: 2020年6月11日 14:36 收件人: electronicarts/CnC_Remastered_Collection <CnC_Remastered_Collection@noreply.github.com&gt; 抄送: yangxujia <yangxujia@qq.com&gt;, Comment <comment@noreply.github.com&gt; 主题: 回复：[electronicarts/CnC_Remastered_Collection] Full Red Alert Dubbing in both Chinese and English[红色警戒配音中/英文] (#30) 都是青春回忆啊，祝各位红警玩家游戏快乐 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

[https://github.com/electronicarts/CnC_Remastered_Collection/issues/15](url)

**Comment by cheenng** [comment]
> 最终编出来只是一个动态库，你们有完整的源码吗 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: 960PRO <notifications@github.com&gt; 发送时间: 2020年6月11日 14:36 收件人: electronicarts/CnC_Remastered_Collection <CnC_Remastered_Collection@noreply.github.com&gt; 抄送: yangxujia <yangxujia@qq.com&gt;, Comment <comment@noreply.github.com&gt; 主题: 回复：[electronicarts/CnC_Remastered_Collection] Full Red Alert Dubbing in both Chinese and English[红色警戒配音中/英文] (#30) 都是青春回忆啊，祝各位红警玩家游戏快乐 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

#15

**Comment by duanzc** [comment]
爷的青春又焕发了

**Comment by babyNEKO** [comment]
青春回忆👍

**Comment by azone** [comment]
有些翻译比较冗长啊~

**Comment by iTruth** [comment]
满满的回忆啊😊

**Comment by LeonYanghaha** [comment]
Mark。

**Comment by qaz6237326** [comment]
这个似乎不是整个游戏的源代码吧

**Comment by JasonkayZK** [comment]
> 这个似乎不是整个游戏的源代码吧

是的，这个已经不是了；
