### ISSUE TITLE
Attaching Visual Studio debugger fails

### ISSUE THREAD

**Issue by Capt-Nemo-** [electronicarts/CnC_Remastered_Collection#46]
Has anyone been able to debug the dll's and step over the code? When I try to attach to the hosting process (InstanceServerG.exe) or the ClientG.exe I get error "Unable to attach to process. A debugger is already attached." But no other debugger is ever attached..theres not even another instance of VS running...I tried to run VS as admin, tried to turn off steam overlay, tried to invoke debugger from code but it crashes :/

**Comment by Kaffeetasse** [comment]
No I have the same problem.
But as a Workaround you can open a console window and output text.
```
    if (AllocConsole()) {
		FILE* console_out = freopen("conout$", "w", stdout);
		char* test = "init complete";
		fputs(test, console_out);
    }
```

**Comment by Capt-Nemo-** [comment]
Yea I'm using various stuff like consoles and message boxes but it's tedious. I wonder if this is intentional as a self-defense against reverse engineering or something. Can't think of anything practical that would cause this kind of error..

**Comment by Capt-Nemo-** [comment]
I implemented primitive custom launcher and renderer that allows for full source stepping, breakpoints and variable inspection.  It loads predefined .sav file and has basic mouse support like clicking on units, moving them, ordering attack, has rectangle selection etc. It's a godsend when you need to find why your mod crashes. For an example how this works see [my repo](https://github.com/Capt-Nemo-/CnCRemasteredCodeRefreshMod). Closing this issue.

**Comment by Einkoro** [comment]
I was able to get the debugger to attach. Easiest way is to fire up cheat engine, select the launcher, and replace FF B7 B0 41 00 00 with FF B7 B0 40 00 00 and you should be able to attach the debugger to the other processes.

**Comment by Capt-Nemo-** [comment]
Neat! Would be nice to be able to step through "production" dll, my custom launcher is still useful for rapid prototyping as it immediately throws you into a mission with almost no loading delay (gdi 1 but could be any save you want) and if it crashes you don't spam petroglyphs servers with exception reports :)

**Comment by codyintar** [comment]
I have some problems for your repo and it cannot run.

**Comment by Capt-Nemo-** [comment]
For the record, there's apparently easier way to attach the debugger. What prevents debugging is just crash handler that can be disabled by adding "NO_EVENT_HANDLER" cmd parameter to the game's launcher...
