### ISSUE TITLE
License Incompatibilty

### ISSUE THREAD

**Issue by snuxoll** [electronicarts/CnC_Remastered_Collection#5]
EA, you have released the code for two DLL's in this repository under the GPL - which I can only assume means there is a separate executable in the released game that will be responsible for loading these and potentially others. Unless you are also planning on releasing the rest of the code when the game is launched, no modder will be able to meet the requirements of the GPL because the GPL'd code will need to be loaded into a proprietary application to function.

If your intention is only for these DLL's to be open source might I recommend switching to the LGPL(v3) license instead? Otherwise more information on future plans would be welcome.

**Comment by Vaporeon** [comment]
The GPL is a distribution license, not a runtime EULA.

**Comment by snuxoll** [comment]
@Vaporeon Your point? Code licensed under the GPL cannot be loaded in a process in which non-GPL compatible code is present, modders cannot legally, under the GPL, modify and redistribute this code with the intent that it is loaded by a proprietary EA executable.

See
https://www.gnu.org/licenses/gpl-faq.en.html#GPLPluginsInNF
https://www.gnu.org/licenses/gpl-faq.en.html#GPLPlugins

**Comment by Metadorius** [comment]
This is a critical flaw which makes it legally impossible to mod remasters engine-wise. EA, please, fix this. The LGPL would be a better alternative here.

**Comment by cleoold** [comment]
Agree +1

**Comment by GraionDilach** [comment]
I think the idea was closer to dual licensing here. Asin GPLv3 + a legal exception to bind it with the C&CR executable. LGPLv3 allows literally no control nor transparency to track where this code would end up and I suspect EA would still an interest on this.

Additionally the C&C modding scene was always in the legally grey area with constantly mixing assets from different entries of the franchise (most notably art and sound) so I think this would still lead to the first bulletpoint in practice anyway.

**Comment by Metadorius** [comment]
@GraionDilach I don't see how "modding was always gray area" makes s valid argument worth mentioning. If they were up to the idea you mentioned - this would've been stated in the license file, but no it's not.

**Comment by GraionDilach** [comment]
The game isn't even released. There's nothing to bind the legal exception to yet.

**Comment by mytbk** [comment]
What's your point? I don't think there's any problem.
1. EA is the copyright holder of this code, so it can use the code in its projects even it's proprietary.
2. If others want to use this code, what they need is only to release their project under GPLv3. Especially, OpenRA can use this without any problem because it's already using GPLv3.

**Comment by OmniBlade** [comment]
No compatibility issue because its the end user, not the modder, who actually links the dll into a proprietary program and the end user is not restricted from doing this by the GPL. The modder is only distributing their dll based on this code and have full rights to do so as granted by the GPL provided they distribute the source to their dll. No exception is even required because EA themselves are the copyright holders and can distribute the dll files under whatever license they choose to, they are not using the GPL as the source of their right to distribute, only modders are.

**Comment by snuxoll** [comment]
> @GraionDilach 
> I think the idea was closer to dual licensing here. Asin GPLv3 + a legal exception to bind it with the C&CR executable. LGPLv3 allows literally no control nor transparency to track where this code would end up and I suspect EA would still maintain an interest on this.

The LGPLv3 only allows removes the requirement that linking requires the entire program be GPL-compatible, requiring instead that the individual library remain available under the terms of the LGPL and that users must be able to replace it with their own version.

> @mytbk 
> EA is the copyright holder of this code, so it can use the code in its projects even it's proprietary.

Yes, the purpose of this release is so modders can modify it for use in the C&C Remastered Collection on launch. Right now that is legally not possible due to the license based an the assumed design, given that EA is explicitly publishing just the source to these two DLL's.

> @OmniBlade 
> The modder is only distributing their dll based on this code and have full rights to do so as granted by the GPL provided they distribute the source to their dll. 

Absolutely incorrect. The GPL explicitly does not allow this kind of usage to prevent it being used as a loophole to load free code into non-free applications. One person freely distributing a shared library that any program and developer can link to and utilize is a verify different scenario than a shared library with an interface exported specifically to be loaded by a proprietary application.

**Comment by Capt-Nemo-** [comment]
I'm toying with an idea to create .NET api layer to allow modders to write plugins and mission scripts in .NET environment. It would mean recompiling the two game dll's and inserting hooks here and there and also write some dynamic loading code to pickup any .NET assemblies and run code inside them etc. The end user would have to replace game's main dll with mine to allow mods to work. What would be the legality of that? Is it possible with current licence?

**Comment by snuxoll** [comment]
@Capt-Nemo- the problem with the current license is that no mod can meet the distribution requirements of the GPL if these libraries are intended to link into an EA provided executable under a non-GPL compatible license.

If they fix this issue (which they could do by releasing under the LGPL or adding a specific linking exception, ideally removable so this could be used with other GPL code outside the remasters) then there’s nothing wrong with this as long as you adhere to the license.

**Comment by OmniBlade** [comment]
@snuxoll The GPL doesn't allow it if you are distributing a none free program with GPL plugins with the intention of avoiding the GPL, that is true. However no modders will be distributing a binary like that so how can they be found in breach of the GPL? They will be distributing all the code to the binary they are distributing. EA can't be in violation since they are the copyright holder and the DLLs they distribute are distributed under that authority.

**Comment by snuxoll** [comment]
Additionally, given the comment from @Capt-Nemo- I don’t believe the LGPL is the right choice for this code, as it would allow mods like this to be published under a different license.

The GPLv3 allows for supplemental terms or additional permissions, so the best way to handle this would be to go that route and allow linking into EA’s executable and have that additional right removed in all other contexts to remain compatible with use in other GPLv3-compatible code.

**Comment by mirh** [comment]
If we were talking about the main program being GPLv3 and the dlls being proprietary, this concern would make sense. You can't even compile your program without the closed libs. 
But it's the other way around here. 
There is a violation indeed, but it resides on the part of the main executable. 
And the offender would be EA (they are linking against GPLv3 code without caring for opening the rest), which is also the copyright holder. So this can work for as much as quite the edge case.

**Comment by snuxoll** [comment]
@mirh the offender would be anyone distributing compiled binaries that do not make up the complete work (i.e. the game executable and all linked libraries). The source itself would be fine in isolation, but without a linking exception nobody can distribute compiled mods intended for use in the game.

References:
https://www.gnu.org/licenses/gpl-faq.en.html#GPLPluginsInNF
https://www.gnu.org/licenses/gpl-faq.en.html#FSWithNFLibs
https://www.gnu.org/licenses/gpl-faq.en.html#GPLIncompatibleLibs

EA need only add a few lines to solve this:

Additional permission under GNU GPL version 3 section 7

If you modify this Program, or any covered work, by linking or combining it with [name of library] (or a modified version of that library), containing parts covered by the terms of [name of library's license], the licensors of this Program grant you additional permission to convey the resulting work. {Corresponding Source for a non-source form of such a combination shall include the source code for the parts of [name of library] used as well as that of the covered work.}

**Comment by mirh** [comment]
>  https://www.gnu.org/licenses/gpl-faq.en.html#GPLIncompatibleLibs

Notice that there's no "what if I use GPL-incompatible software with GPL libraries". 
Only linking is the "possibly offensive" act. And if you are just building the starting library to begin with, then this is not a concern. 

>  https://www.gnu.org/licenses/gpl-faq.en.html#GPLPluginsInNF

Credit where it is due. 
A *loading executable* **could** be at fault for loading a GPL library.
But you can't have the library being at fault for.. *being loaded*. 

Are you one of the OpenRA guys? Then you are perfectly fine and there's no way anything should not check out. 
Are you EA with a proprietary exe? Shame on you, and you are violating the license. There are no technical loopholes here. 
https://www.gnu.org/licenses/gpl-faq.en.html#WhoHasThePower
But at the same time they are the original copyright holder, so unless you are suggesting they may get sued by themselves, this doesn't make sense from a logical point of view. 

*On the other hand*, it would still be nice if they could properly add that exception (or dual license, or whatever). If not any from a "technically correct is the best kind of correct" perspective. And in light of possible future community contributions?
But it's not really *that* crazy.

**Comment by OmniBlade** [comment]
I doubt they will accept community contributions without copyright assignment for that very reason. As you say, only linking is the offense and the end user will be doing that, not the modder distributing a compiled dll. That would be like saying that if I distributed a modifed libavcodec  and someone loaded it in a closed source binary that I would be liable for the GPL violation.

**Comment by GraionDilach** [comment]
@mirh To your question, @snuxoll has never been involved with OpenRA.

Out of all the posters here so far, @OmniBlade is a member of @TheAssemblyArmada whose Chronoshift project actually benefits more from this repository than ORA's own clean-room reimplementations, @Metadorius is the administrator of the TS/RA2 modding community Discord hub and I'm a very divisive person in both the TS/RA2 and the OpenRA community with a history in both.

**Comment by hardliner66** [comment]
> Code licensed under the GPL cannot be loaded in a process in which non-GPL compatible code is present.

This is plain wrong. If this where true, no one could write GPL plugins for proprietary software.

The GPL only disallows derivative works inkluding linking. But because the engine isn't derivative work **and** the engine is created by the licenseholder of this source code, this doesn't apply here.

**Comment by snuxoll** [comment]
Okay, after reviewing the FSF’s guidance, the license itself and the source code the only issue not having a linking exception causes is EA’s own inability to take changes without a CLA with either assignment or permissive license. None of the code here calls functions exposed by the assumed engine that will be loading this code and has been properly isolated into a complete work, you can see all of the relevant exports in DllInterface.cpp and friends.

I’d still personally like to see a linking exception to prevent the need for a CLA, but I do agree now upon review that it’s not necessary for modders to use and redistribute modified binaries. As such I am marking this issue as closed, EA can figure out how they want to handle contributions (if they even want them).
