### ISSUE TITLE
How about REDALERT Linux version

### ISSUE THREAD

**Issue by jason-bowen-zheng** [electronicarts/CnC_Remastered_Collection#76]
I always use Linux, but I found that this was Windows version
> I don't like wine

So, can you rewrite the code or just add a `Makefile`.

**Comment by hifi** [comment]
There's #31 with multiple projects trying to achieve this.

**Comment by jason-bowen-zheng** [comment]
REDALERT is an excellent game, but it just support Windows platform`:(`.

It seems incomprehensible. Share make good things better!

I also know there are many different things between Windows and Linux.

I saw #31. I agree with `alexlk42`. So we should wait patiently until Linux version appears.

I'm just a beginner, but multi platform support is my dream. Let's realize it!

**Comment by Mortecha** [comment]
It works fine under Proton

**Comment by jason-bowen-zheng** [comment]
I forgot close this
